# Generated by Django 5.2.12 on 2026-03-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('title_en', models.CharField(blank=True, default='', max_length=512)),
                ('title_ru', models.CharField(blank=True, default='', max_length=512)),
                ('description_en', models.TextField(blank=True)),
                ('features_en', models.TextField(blank=True)),
                ('categories_en', models.CharField(blank=True, max_length=512)),
                ('description_ru', models.TextField(blank=True)),
                ('features_ru', models.TextField(blank=True)),
                ('categories_ru', models.CharField(blank=True, max_length=512)),
                ('price', models.FloatField(blank=True, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('rating_number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'item_detail',
            },
        ),
    ]
